name: java-workflow

on:
  workflow_call:
    inputs:
      skip-codeql-step:
        type: boolean
        required: false
        default: true

jobs:
  tests-and-quality-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Build
        run: mvn -B clean verify

      - name: Initialize CodeQL
        if: inputs.skip-codeql-step == false
        uses: malurneelima/ci-workflow/.github/actions/codeql/codeql-scan-java@v4
        with:
          languages: java-kotlin
          build-mode: autobuild

